server:
  port: 8000

spring:
  config:
    import: nacos:service-order.yaml
  application:
    name: service-order

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.20:8848

      config:
        server-addr: 192.168.0.20:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        name: service-order
        import-check:
          enabled: false

seata:
  enabled: false
